name: Build ISO

on:
  push:
    branches: [ bare-minimal-linux ]
  pull_request:
    branches: [ bare-minimal-linux ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # how man commits do we fetch? we need enough so that we have a tagged commit as well else the build will fail
        fetch-depth: '20'
    # workaround for fetching tags from https://github.com/actions/checkout/issues/290 as the action does not fetch tags, even when all commits are fetched
    - name: get git tags
      run: |
        git fetch --tags --force
    - name:
      run: |
        git describe --tags --abbrev=0
        git rev-parse --short HEAD
    - name: install prerequsites
      run: |
        sudo apt install automake libtool pkg-config # lldpd
        sudo apt install wget make gawk gcc bc bison flex xorriso libelf-dev libssl-dev xz-utils cpio file build-essential g++ # minimal linux
        sudo apt install pkg-config upx upx-ucl # lshw
    - name: build iso
      run: |
        cd src
        yes "" | sudo ./build_minimal_linux_live.sh
    - name: upload iso as artifact
      uses: actions/upload-artifact@v2
      with:
        name: bare-minimal-linux.iso
        path: src/minimal_linux_live.iso

