name: Build ISO

on:
  push:
    branches: [ bare-minimal-linux ]
  pull_request:
    branches: [ bare-minimal-linux ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # how man commits do we fetch? we need enough so that we have a tagged commit as well else the build will fail
        fetch-depth: '20'
    # workaround for fetching tags from https://github.com/actions/checkout/issues/290 as the action does not fetch tags, even when all commits are fetched
    - name: get git tags
      run: |
        git fetch --tags --force
    - name:
      run: |
        git describe --tags --abbrev=0
        git rev-parse --short HEAD
        
    - name: ccache-${{ github.job }}
      uses: hendrikmuhs/ccache-action@v1.2.2
      with:
        key: ${{ github.job }}-${{ runner.os }} # Eg. "some_build-ubuntu-latest"
        max-size: 500M
        verbose: 2
        # variant: sccache
    - name: 'Add /usr/lib/ccache:/usr/local/opt/ccache/libexec to $PATH'
      run: |
        echo "/usr/local/opt/ccache/libexec" >> $GITHUB_PATH
        echo "/usr/lib/ccache" >> $GITHUB_PATH
        
    - name: install prerequsites
      run: |
        sudo apt install automake libtool pkg-config # lldpd
        sudo apt install wget make gawk gcc bc bison flex xorriso libelf-dev libssl-dev xz-utils cpio file build-essential g++ # minimal linux
        sudo apt install pkg-config upx upx-ucl # lshw
    - name: build iso
      run: yes "" | sudo ./build_minimal_linux_live.sh
      working-directory: ./src
    - name: upload iso as artifact
      uses: actions/upload-artifact@v2
      with:
        name: bare-minimal-linux.iso
        path: src/minimal_linux_live.iso
