
on:
  push:
    branches: [ bare-minimal-linux ]
  pull_request:
    branches: [ bare-minimal-linux ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: apt Install
      run: |
        apt update
        apt install automake libtool pkg-config # lldpd
        apt install wget make gawk gcc bc bison flex xorriso libelf-dev libssl-dev xz-utils cpio file build-essential # minimal linux
        apt install pkg-config upx-ucl # lshw

    - name: build_minimal_linux_live.sh
      run: |
        cd src
        ./build_minimal_linux_live.sh
