
on:
  push:
    branches: [ bare-minimal-linux ]
  pull_request:
    branches: [ bare-minimal-linux ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.os }}-${{ matrix.type }}
        max-size: 100M

    - name: apt Install
      run: |
        sudo apt update
        sudo apt install automake libtool pkg-config # lldpd
        sudo apt install wget make gawk gcc bc bison flex xorriso libelf-dev libssl-dev xz-utils cpio file build-essential # minimal linux
        sudo apt install pkg-config upx-ucl # lshw

    - name: build_minimal_linux_live.sh
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cd src
        ./build_minimal_linux_live.sh
