name: publish bml

# Controls when the workflow will run
on:
  # might need to be adjusted to somehow use tags instead of releases
  release:
    types: [published, created, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: bare-minimal-linux.iso
          # Destination path
          path: bare-minimal-linux.iso
          
      # use rsync and ssh to put the iso to the right folder
      - name: push iso via rsync over ssh
        run: |
          echo "add SSH-key to agent from secret"
          echo something
          # copy iso to jumphost and use the git tag as filename
          echo rsync bare-minimal-linux.iso bml@jump01.cc.eu-de-1.cloud.sap/repo/iso/$(git tag ...).iso
